### ISSUE TITLE
Create a workflow that updates the github action pins

### ISSUE THREAD

**Issue by pskrbasu** [turbot/steampipe-workflows#70]
Create a central workflow which is used by pipeline repos that updates the GitHub action pins in the workflows.

Something like this:
```
name: Pin GitHub Actions

on:
  schedule:
    - cron: '0 0 */14 * *'  # Every 14 days at midnight UTC
  workflow_dispatch:         # Also allow manual triggering

jobs:
  pin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Run pinact-action
        uses: suzuki-shunsuke/pinact-action@v0.1.2
        with:
          skip_push: "false"

      - name: Check for changes
        id: git_diff
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "changes=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Create PR if changes found
        if: steps.git_diff.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: pin GitHub Actions with pinact"
          title: "chore: pin GitHub Actions"
          body: "This PR was created automatically by the pinact-action workflow. It updates unpinned or outdated actions."
          branch: pinact/update-actions
          delete-branch: true
```
